# Site settings
title: "jaehoonman"
bye_message: "떙큐 떙큐"
baseurl: ""
url: "https://wido1593.github.io"
#disqus: gjuniioor

# Header settings
nick: "jaehoonman"
mail:
    domain: "wido1593"
    ext: "g"
source_code:
    server: "github.com"
    nick: "wido1593"
blog:
    server: "tistory.com"
    nick: "jaehoonman"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
future: true #post 작성 시 미래의 날짜도 개시할 것인지.

# 헤더 두 번 나타나는거 수정.
titles_from_headings:
    enabled:     true
    strip_title: false
    collections: false