# Site settings
title: "jaehoonman"
bye_message: "떙큐 떙큐"
baseurl: "/jaehoonman/"
url: "https://wido1593.github.io"
#disqus: gjuniioor

# Header settings
nick: "jaehoonman"
mail:
    domain: "wido1593"
    ext: "g"
source_code:
    server: "github.com"
    nick: "wido1593"
blog:
    server: "tistory.com"
    nick: "jaehoonman"
#fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
future: true #post 작성 시 미래의 날짜도 개시할 것인지.